#!/bin/bash

COLOR=96
STAGGED_FILES=$(git diff --cached --name-only)

echo -e "\e[1;${COLOR}m-- GIT HOOK : format source files with Black --\e[1;0m"
for FILE in ${STAGGED_FILES}; do
  if [ -f "$FILE" ] && [[ $FILE == *.py ]]; then
    black $FILE || exit 1
  fi
done

echo -e "\e[1;${COLOR}m-- GIT HOOK : run tests with pytest --\e[1;0m"
pytest

for FILE in ${STAGGED_FILES}; do
  git add $FILE
done
