#!/bin/bash

COLOR=96
STAGGED_FILES=$(git diff --cached --name-only)

echo -e "\e[1;${COLOR}m-- GIT HOOK : format source files with Black --\e[1;0m"
for FILE in ${STAGGED_FILES}; do
  if [ -f "$FILE" ] && [[ $FILE == *.py ]]; then
    black $FILE
  fi
done

echo -e "\e[1;${COLOR}m-- GIT HOOK : format inclusions with isort & autoflake --\e[1;0m"
autoflake --in-place --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports *.py utility/*.py tests/*.py
isort .

echo -e "\e[1;${COLOR}m-- GIT HOOK : run tests with pytest --\e[1;0m"
./check || exit 1

for FILE in ${STAGGED_FILES}; do
  git add $FILE
done
