name: Check Installation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install ccache python3.11-dev python3.11-venv
    - run: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 20
    - run: curl -sSL https://install.python-poetry.org | POETRY_HOME=/usr/local/poetry sudo python3.11 -
    - run: export PATH=/usr/local/poetry/bin:$PATH
    - run: poetry install
    - run: >-
        echo '
          alert
          timmed_alert
          error
          banner
          panic
        ' | python3 examples/demo.py
