name: Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install ccache
    - run: pip3 install pip --upgrade 
    - run: pip3 install pip --upgrade 
    - run: python3 -m venv venv
    - run: source venv/bin/activate
    - run: pip install .
    - run: poetry run pytest -s --timeout 3
