name: Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install ccache python3.11-dev python3.11-venv
    - run: sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 20
    - run: pip3 install pip --upgrade 
    - run: pip3 install pip --upgrade 
    - run: python3 -m venv venv
    - run: source venv/bin/activate
    - run: pip install .
    - run: poetry run pytest -s --timeout 3
