name: Check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install ccache
    - run: pip3 install pip --upgrade 
    - run: ./configure
    - run: ./check --timeout 3
